apiVersion: v1
kind: Service
metadata:
  name: afjhb1-nginx-prod-001          # Updated active service name
  namespace: demo                       #
spec:
  selector:
    app: afjhb1-nginx-demo              # Points to the new rollout application label
  ports:
    - port: 8080                        #
      targetPort: 8080                  #
  type: LoadBalancer                    #
