apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-secure
  namespace: demo

spec:
  replicas: 3
  revisionHistoryLimit: 2
  
  strategy:
    blueGreen:
      activeService: nginx-active
      previewService: nginx-preview
      autoPromotionEnabled: false

  selector:
    matchLabels:
      app: nginx-secure

  template:
    metadata:
      labels:
        app: nginx-secure

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: nginx-secure

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: nginx
          image: ghcr.io/olivierh-af/nginx-demo-app:bcc71a6cfc44280525e962ca171d8d789dcd6c68

          ports:
            - containerPort: 8080

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
