apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-secure
spec:
  replicas: 3

  strategy:
    blueGreen:
      activeService: nginx-active
      previewService: nginx-preview
      autoPromotionEnabled: false
      
  selector:
    matchLabels:
      app: nginx-secure

  template:
    metadata:
      labels:
        app: nginx-secure
    spec:
    topologySpreadConstraints:26      
    - maxSkew: 127
      topologyKey: kubernetes.io/hostname28
      whenUnsatisfiable: DoNotSchedule29
      labelSelector:30
        matchLabels:31
          app: nginx-secure
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:mainline-alpine
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
